//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// Base class for all 
[Serializable]
public class Box {
    /// <summary>
    /// Constructor
    /// </summary>
    public Box() {
    }

}

