//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

private class BoxFactory : IBoxFactory
{
	protected IEnumerable<Box> _box;

	public virtual Box getBox(EBoxType boxType)
	{
		throw new System.NotImplementedException();
	}

	public BoxFactory()
	{
	}

}

