//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SourceProject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

private class BoxFactory : IBoxFactory
{
	protected IEnumerable<Box> _box;

	public virtual Box getBox(EBoxType boxType)
	{
		throw new System.NotImplementedException();
	}

	public BoxFactory()
	{
	}

	public virtual Box getBox(EBoxType boxType)
	{
		throw new System.NotImplementedException();
	}

}

