//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SourceProject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BoxFactory : IBoxFactory
{
	protected Box _desertBox;
    protected Box _forestBox;
    protected Box _lowlandBox;
    protected Box _mountainBox;
    protected Box _seaBox;

	public virtual Box getBox(EBoxType boxType)
	{
        Box box;
		switch(boxType)
        {
            case EBoxType.DESERT:
                box =  _desertBox;
                break;

            case EBoxType.FOREST:
                box = _forestBox;
                break;

            case EBoxType.LOWLAND:
                box = _lowlandBox;
                break;

            case EBoxType.MOUTAIN:
                box = _mountainBox;
                break;

            case EBoxType.SEA:
                box = _seaBox;
                break;

            default:
                box = null;
                break;
        }
        return box;
	}

	public BoxFactory()
	{
        _desertBox = new DesertBox();
        _forestBox = new ForestBox();
        _lowlandBox = new LowlandBox();
        _mountainBox = new MountainBox();
        _seaBox = new SeaBox();
	}

}

