//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DemoGameBuilder : GameBuilder
{
	public DemoGameBuilder(ENation nation1, ENation nation2)
	{
        Map map = new DemoMap();
        _game.setMap(map);
        _unitNumber = 4;
        _game.setMaxSteps(5);
        createPlayers(nation1, nation2);
	}

}

