//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DemoMap : Map
{
	public DemoMap()
	{
        Width = 5;
        Height = 5;
        _map = new Box[Height, Width];
        List<int> generatedMap = wrapperAlgo.mapGeneration(Height * Width, Enum.GetNames(typeof(EBoxType)).Length);

        convertIntListToMap(generatedMap);
	}

}

