//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// The desert box
/// </summary>
public class DesertBox : Box {
    /// <summary>
    /// Constructor
    /// </summary>
    public DesertBox() {
    }

}

