//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Enumeration used to specify the game type
/// </summary>
public enum EGameType : int {

    DEMO,
    NORMAL,
    SMALL,
}
