//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameDirector : IGameDirector
{
	protected GameBuilder _builder;

	public virtual void buildGame(EGameType gameType, ENation nation1, ENation nation2)
	{
		throw new System.NotImplementedException();
	}

	public GameDirector()
	{
	}

}

