//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameDirector : IGameDirector
{
	protected GameBuilder _builder;

	public virtual void buildGame(EGameType gameType, ENation nation1, ENation nation2)
	{
		throw new System.NotImplementedException();
	}

	public GameDirector()
	{
	}

}

