//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

private class Game : IGame
{
	protected Map _map;

	protected Player _player1;

	protected Player _player2;

	public virtual void setMap(Map map)
	{
		throw new System.NotImplementedException();
	}

	public virtual void setMaxSteps(int max)
	{
		throw new System.NotImplementedException();
	}

	public virtual Player getActivePlayer()
	{
		throw new System.NotImplementedException();
	}

	public Game()
	{
	}

	public virtual void checkWinner()
	{
		throw new System.NotImplementedException();
	}

	public virtual void endOfPlay()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool fight()
	{
		throw new System.NotImplementedException();
	}

	public virtual Player getWinner()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool move()
	{
		throw new System.NotImplementedException();
	}

	public virtual void onPropertyChanged()
	{
		throw new System.NotImplementedException();
	}

	public virtual void start()
	{
		throw new System.NotImplementedException();
	}

}

