//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GaulUnit : Unit {
    public GaulUnit() {
    }

    public override int getPoint(Map m) {
        Box b = m.getBox(_line, _column);
        
        if(b.GetType() == typeof(LowlandBox))
            return 2;
        else if (b.GetType() == typeof(MountainBox))
            return 0;
        else
            return 1;
    }
}

