//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

internal interface IUnit 
{
	bool attack(int x, int y);

	void getBox();

	void getDefensive();

	void getLifePoints();

	void getOffensive();

	int getPoint();

	bool move(int x, int y);

	bool setLifePoints(int value);

}

