//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

internal interface IUnit 
{
	bool attack(int x, int y);

	void getBox();

	void getDefensive();

	void getLifePoints();

	void getOffensive();

	int getPoint();

	bool move(int x, int y);

	bool setLifePoints(int value);

}

