//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
/// <summary>
/// The lowland box
/// </summary>
public class LowlandBox : Box {
    /// <summary>
    /// Constructor
    /// </summary>
    public LowlandBox() {
    }

}

