//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SourceProject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Map : IMap
{
	private BoxFactory fabriqueCase;

	protected Box[,] _map;

    public int Width
    {
        get;
        set;
    }

    public int Height
    {
        get
        {
            throw new System.NotImplementedException();
        }
        set
        {
        }
    }

	public virtual void genererCarte()
	{
		throw new System.NotImplementedException();
	}

	public virtual void refreshMap()
	{
		throw new System.NotImplementedException();
	}

	public virtual void showMap()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setBox(Box box, int x, int y)
	{
		throw new System.NotImplementedException();
	}

    public virtual Box getBox(int x, int y)
    {
        return _map[x, y];
    }

	public virtual void addNation(Nation nation)
	{
		throw new System.NotImplementedException();
	}

	public virtual IEnumerable<IEnumerable<int> > getInitCoordonates()
	{
		throw new System.NotImplementedException();
	}

	public Map()
	{
	}
}

