//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Nation : INation
{
	private IEnumerable<Unit> units;

	private UnitFactory unitFactory;

	public virtual void createUnits(int nombreUnites)
	{
		throw new System.NotImplementedException();
	}

	public virtual void getUnits()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getUnitsNumber()
	{
		throw new System.NotImplementedException();
	}

	public Nation(ENation nation, int unitNumber)
	{
	}

	public virtual void setInitBox(int x, int y)
	{
		throw new System.NotImplementedException();
	}

}

