//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SourceProject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Nation : INation {

    private IEnumerable<Unit> units;
    private IUnitFactory<Unit> unitFactory;
    public ENation nationType {
        set;
        get;
    }

    public Nation(ENation nation, int unitNumber) {
        nationType = nation;

        switch(nationType) {
            case ENation.GAUL:
                unitFactory = new UnitFactory<GaulUnit>();
                break;

            case ENation.NAIN:
                unitFactory = new UnitFactory<NainUnit>();
                break;

            case ENation.VIKING:
                unitFactory = new UnitFactory<VikingUnit>();
                break;
        }

        units = unitFactory.getUnits(unitNumber);

    }

    public virtual int getUnitsNumber() {
        return units.Count();
    }

    public virtual IEnumerable<Unit> getUnits() {
        return units;
    }

    public virtual void deleteDeadUnits() {
        units = units.Where(u => u.isAlive());
    }

    public virtual Unit getUnit(int i) {
        return units.ElementAt(i);
    }

    public virtual bool setInitBox(int line, int column, Map m) {
        bool move = true;
        foreach(Unit u in units) {
            move = move && u.move(line, column, m);
            u.initMovePoints();
        }
        if (!move) {
            foreach (Unit u in units) {
                u.nullPosition();
            }
        }
        return move;
    }


    internal void initMovePoints() {
        foreach (Unit u in units)
            u.initMovePoints();
    }
}

