//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NormalGameBuilder : GameBuilder
{
	public NormalGameBuilder()
	{
        Map map = new NormalMap();
        _game.setMap(map);
	}

}

