//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Player : IPlayer
{
	private string _name;

	private Nation _nation;

	private int _unitMaxNb;

	private int _points;

	public virtual void setNation(Nation nation)
	{
		throw new System.NotImplementedException();
	}

	public virtual string getName()
	{
		throw new System.NotImplementedException();
	}

	public virtual Nation getNation()
	{
		throw new System.NotImplementedException();
	}

	public virtual void refresh()
	{
		throw new System.NotImplementedException();
	}

	public Player()
	{
	}

}

