//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SmallMap : Map {
    /// <summary>
    /// Constructor : build a 10x10 map
    /// </summary>
    public SmallMap() {
        Width = 10;
        Height = 10;
        generateMap();
    }

}

