//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SourceProject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Unit : IUnit
{
	private int _defensive;

	private int _lifePoints;

	private int _offensive;

    private int _x;

    private int _y;

	public virtual bool setLifePoints(int value)
	{
		throw new System.NotImplementedException();
	}

	public virtual void getBox()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getDefensive()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getLifePoints()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getOffensive()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getPoint()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool move(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool attack(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public Unit()
	{
	}

	public virtual bool hasMoves()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool attack(Unit defUnit)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool isAlive()
	{
		throw new System.NotImplementedException();
	}
}

