//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SourceProject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class UnitFactory<T> : IUnitFactory<T> where T : Unit, new() {
    public UnitFactory() {
    }

    public virtual IEnumerable<Unit> getUnits(int unitNumber) {
        List<Unit> unitList = new List<Unit>();

        for(int i = 0; i < unitNumber; i++) {
            unitList.Add(new T());
        }
        return unitList;
    }

}

