//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Unit : IUnit
{
	private int _defensive;

	private int _lifePoints;

	private int _offensive;

	public virtual bool setLifePoints(int value)
	{
		throw new System.NotImplementedException();
	}

	public virtual void getBox()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getDefensive()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getLifePoints()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getOffensive()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getPoint()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool move(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool attack(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public Unit()
	{
	}

}

