//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SourceProject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Unit : IUnit
{
	private int _defensive;

	private int _lifePoints;

	private int _offensive;

    private int _line;

    private int _column;

    private double _movePoints;

    public Unit()
    {
        _lifePoints = 5;
        _movePoints = 1;
        _defensive = 1;
        _offensive = 2;
    }

	public virtual bool setLifePoints(int value)
	{
		throw new System.NotImplementedException();
	}

	public virtual int getLine()
	{
		return _line;
	}

    public virtual int getColumn()
    {
        return _column;
    }

	public virtual void getDefensive()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getLifePoints()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getOffensive()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getPoint()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool move(int line, int column)
	{
        _line = line;
        _column = column;

        return true;
	}

	public virtual bool attack(int line, int column)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool hasMoves()
	{
		return _movePoints > 0;
	}

	public virtual bool attack(Unit defUnit)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool isAlive()
	{
		throw new System.NotImplementedException();
	}
}

