//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class UnitFactory : IUnitFactory
{
	public UnitFactory()
	{
	}

	public virtual System::Collections::Generic::IEnumerable<Unit> getUnits(int unitNumber)
	{
		throw new System.NotImplementedException();
	}

}

