//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class UnitFactory : IUnitFactory
{
	public UnitFactory()
	{
	}

	public virtual IEnumerable<Unit> getUnits(int unitNumber)
	{
		throw new System.NotImplementedException();
	}

}

